name: workflow_02
on: 
  repository_dispatch:
  workflow_dispatch:
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering Wokflow 2"
      - name: Checkout
        uses: actions/checkout@v2
      - name: run some command
        run: echo "Ending Wokflow 2"
